const type = {
    ADD: "ADD",
    EDIT: "EDIT",
    ADD_PRODUCT: "ADD_PRODUCT",
    EDIT_PRODUCT: "EDIT_PRODUCT",
    DELETE_PRODUCT: "DELETE_PRODUCT",
    GET_EDITING_PRODUCT: "GET_EDITING_PRODUCT"
}

export default type;